package org.nishkarma.petclinic.repository;

import java.util.List;

import org.nishkarma.petclinic.model.Specialties;
import org.springframework.dao.DataAccessException;

public interface SpecialtiesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table specialties
	 * 
	 * @mbggenerated Thu Aug 01 17:41:56 KST 2013
	 */
	List<Specialties> findAll() throws DataAccessException;

}