package org.nishkarma.book.model;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.hibernate.validator.constraints.NotEmpty;

@XmlRootElement
public class Book {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column book.ID
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column book.TITLE
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	@NotNull
	@Size(min = 2, max = 50)
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column book.AUTHOR
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	@NotEmpty
	private String author;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column book.COVER
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	private Cover cover;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column book.PUBLISHEDYEAR
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	private Integer publishedyear;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column book.AVAILABLE
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	private Boolean available;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column book.COMMENTS
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	private String comments;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column book.ID
	 * 
	 * @return the value of book.ID
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column book.ID
	 * 
	 * @param id
	 *            the value for book.ID
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column book.TITLE
	 * 
	 * @return the value of book.TITLE
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column book.TITLE
	 * 
	 * @param title
	 *            the value for book.TITLE
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column book.AUTHOR
	 * 
	 * @return the value of book.AUTHOR
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column book.AUTHOR
	 * 
	 * @param author
	 *            the value for book.AUTHOR
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column book.COVER
	 * 
	 * @return the value of book.COVER
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public Cover getCover() {
		return cover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column book.COVER
	 * 
	 * @param cover
	 *            the value for book.COVER
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public void setCover(Cover cover) {
		this.cover = cover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column book.PUBLISHEDYEAR
	 * 
	 * @return the value of book.PUBLISHEDYEAR
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public Integer getPublishedyear() {
		return publishedyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column book.PUBLISHEDYEAR
	 * 
	 * @param publishedyear
	 *            the value for book.PUBLISHEDYEAR
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public void setPublishedyear(Integer publishedyear) {
		this.publishedyear = publishedyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column book.AVAILABLE
	 * 
	 * @return the value of book.AVAILABLE
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public Boolean getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column book.AVAILABLE
	 * 
	 * @param available
	 *            the value for book.AVAILABLE
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public void setAvailable(Boolean available) {
		this.available = available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column book.COMMENTS
	 * 
	 * @return the value of book.COMMENTS
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column book.COMMENTS
	 * 
	 * @param comments
	 *            the value for book.COMMENTS
	 * 
	 * @mbggenerated Thu Aug 22 16:55:11 KST 2013
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	public boolean isNew() {
		return (this.id == 0);
	}

	@Override
	public String toString() {
		return new ToStringBuilder(this).append("id", id)
				.append("author", author).append("title", title)
				.append("publishedYear", publishedyear)
				.append("available", available).append("cover", cover)
				.toString();
	}

}