package org.nishkarma.petclinic.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.validation.constraints.Digits;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;

public class Owners {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column owners.id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column owners.first_name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	@NotEmpty
	private String firstName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column owners.last_name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	@NotEmpty
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column owners.address
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	@NotEmpty
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column owners.city
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	@NotEmpty
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column owners.telephone
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	@NotEmpty
	@Digits(fraction = 0, integer = 10)
	private String telephone;

	// to prevent JSON infinite recursion at bi-directional relationship
	// lsj
	private Set<Pets> pets;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column owners.id
	 * 
	 * @return the value of owners.id
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column owners.id
	 * 
	 * @param id
	 *            the value for owners.id
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column owners.first_name
	 * 
	 * @return the value of owners.first_name
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column owners.first_name
	 * 
	 * @param firstName
	 *            the value for owners.first_name
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column owners.last_name
	 * 
	 * @return the value of owners.last_name
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column owners.last_name
	 * 
	 * @param lastName
	 *            the value for owners.last_name
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column owners.address
	 * 
	 * @return the value of owners.address
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column owners.address
	 * 
	 * @param address
	 *            the value for owners.address
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column owners.city
	 * 
	 * @return the value of owners.city
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column owners.city
	 * 
	 * @param city
	 *            the value for owners.city
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column owners.telephone
	 * 
	 * @return the value of owners.telephone
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column owners.telephone
	 * 
	 * @param telephone
	 *            the value for owners.telephone
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public boolean isNew() {
		return (this.id == null);
	}

	protected void setPetsInternal(Set<Pets> pets) {
		this.pets = pets;
	}

	protected Set<Pets> getPetsInternal() {
		if (this.pets == null) {
			this.pets = new HashSet<Pets>();
		}
		return this.pets;
	}

	public List<Pets> getPets() {
		List<Pets> sortedPets = new ArrayList<Pets>(getPetsInternal());
		PropertyComparator.sort(sortedPets, new MutableSortDefinition("name",
				true, true));
		return Collections.unmodifiableList(sortedPets);
	}

	public void addPet(Pets pet) {
		getPetsInternal().add(pet);
		pet.setOwner(this);
	}

	/**
	 * Return the Pet with the given name, or null if none found for this Owner.
	 * 
	 * @param name
	 *            to test
	 * @return true if pet name is already in use
	 */
	public Pets getPet(String name) {
		return getPet(name, false);
	}

	/**
	 * Return the Pet with the given name, or null if none found for this Owner.
	 * 
	 * @param name
	 *            to test
	 * @return true if pet name is already in use
	 */
	public Pets getPet(String name, boolean ignoreNew) {
		name = name.toLowerCase();
		for (Pets pet : getPetsInternal()) {
			if (!ignoreNew || !pet.isNew()) {
				String compName = pet.getName();
				compName = compName.toLowerCase();
				if (compName.equals(name)) {
					return pet;
				}
			}
		}
		return null;
	}

}