package org.nishkarma.petclinic.model;

public class Specialties {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column specialties.id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column specialties.name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column specialties.id
	 * 
	 * @return the value of specialties.id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column specialties.id
	 * 
	 * @param id
	 *            the value for specialties.id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column specialties.name
	 * 
	 * @return the value of specialties.name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column specialties.name
	 * 
	 * @param name
	 *            the value for specialties.name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}
}