package org.nishkarma.petclinic.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.xml.bind.annotation.XmlElement;

import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;

public class Vets {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column vets.id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column vets.first_name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	private String firstName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column vets.last_name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	private String lastName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column vets.id
	 * 
	 * @return the value of vets.id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */

	private Set<Specialties> specialties;

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column vets.id
	 * 
	 * @param id
	 *            the value for vets.id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column vets.first_name
	 * 
	 * @return the value of vets.first_name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column vets.first_name
	 * 
	 * @param firstName
	 *            the value for vets.first_name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column vets.last_name
	 * 
	 * @return the value of vets.last_name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column vets.last_name
	 * 
	 * @param lastName
	 *            the value for vets.last_name
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	protected void setSpecialtiesInternal(Set<Specialties> specialties) {
		this.specialties = specialties;
	}

	protected Set<Specialties> getSpecialtiesInternal() {
		if (this.specialties == null) {
			this.specialties = new HashSet<Specialties>();
		}
		return this.specialties;
	}

	@XmlElement
	public List<Specialties> getSpecialties() {
		List<Specialties> sortedSpecs = new ArrayList<Specialties>(
				getSpecialtiesInternal());
		PropertyComparator.sort(sortedSpecs, new MutableSortDefinition("name",
				true, true));
		return Collections.unmodifiableList(sortedSpecs);
	}

	public int getNrOfSpecialties() {
		return getSpecialtiesInternal().size();
	}

	public void addSpecialty(Specialties specialty) {
		getSpecialtiesInternal().add(specialty);
	}

}