package org.nishkarma.petclinic.model;

public class VetSpecialties {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column vet_specialties.vet_id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	private Integer vetId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column vet_specialties.specialty_id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	private Integer specialtyId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column vet_specialties.vet_id
	 * 
	 * @return the value of vet_specialties.vet_id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public Integer getVetId() {
		return vetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column vet_specialties.vet_id
	 * 
	 * @param vetId
	 *            the value for vet_specialties.vet_id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setVetId(Integer vetId) {
		this.vetId = vetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column vet_specialties.specialty_id
	 * 
	 * @return the value of vet_specialties.specialty_id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public Integer getSpecialtyId() {
		return specialtyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column vet_specialties.specialty_id
	 * 
	 * @param specialtyId
	 *            the value for vet_specialties.specialty_id
	 * 
	 * @mbggenerated Thu Aug 01 15:43:11 KST 2013
	 */
	public void setSpecialtyId(Integer specialtyId) {
		this.specialtyId = specialtyId;
	}
}